### ISSUE TITLE
Example issue

### ISSUE THREAD

**Issue by janboone** [janboone/applied-economics#1]
Here you type your question.

Then click on the "Submit new issue" button.

**Comment by SJMKamsma** [comment]
Dear Jan Boone,
When converting my md file in an html file using pandoc, I got the following error: Cannot decode byte '\x92': Data.Text.Internal.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream. When looking at the internet, this is an error because I have some accented characters in my file. However, when trying to fix this with the codes they explain online, the converting does not work. What can I do to avoid this so I can convert my md file into a html file. 
Regards,
Sietske

**Comment by janboone** [comment]
Just to be sure: when you delete the special characters, the conversion to html works fine?

If so, then check this page and the two references in the question:

http://stackoverflow.com/questions/21224741/special-characters-not-showing-in-pandoc-html-output

**Comment by SJMKamsma** [comment]
Dear Jan Boone,

When I deleted those special characters, it did give the same error
unfortunately.
Is there something else I should do?

Regards,
Sietske

**Comment by janboone** [comment]
did you put your markdown file on github? Can you send me the link to this file?

**Comment by SJMKamsma** [comment]
The markdown file can be found via this link.
https://github.com/SJMKamsma/Assignments The CV.md file is the file that
needs to be converted.
Thank you for your time!

Regards,
Sietske

**Comment by janboone** [comment]
go to the CV.md file and click on `Raw`: this gives

https://raw.githubusercontent.com/SJMKamsma/Assignments/master/CV.md

As you can see, your editor has inserted an odd character (�) in your md file. Delete all these characters and pandoc works.

**Comment by RobbertvanRiel** [comment]
Dear Jan,

I'm trying to convert my CV written in Latex into .html in order to upload it on Github. However I failed to upload it. At first I tried to convert it from .tex to .pdf to .html this did not really work out well. Secondly I tried to convert the .tex file to .text using command pandoc -s cv.tex -o cv.text
Using this command nearly all content of my .tex disappeared and only the titles such as Educations, Experience etc remained. So far, I did not manage to upload my cv.

How can I upload my .tex file on github without losing content?

p.s I tried to attach the .tex , .text and .html but github does not support these. I ended the files to your tilburguniversity.edu mail
