### ISSUE TITLE
Notebook - Asymmetric Information

### ISSUE THREAD

**Issue by MateoMalbasic** [janboone/applied-economics#25]
In the first part of Asymmetric Information we got the following question:
Show graphically the effect of an increase in income on the market outcome. Does the inefficiency increase or decrease with income? Why?

By increasing the income one could see that the equilibrium will change and less people will be insured which decreses the efficiency. 
But why is this the reason, that in this case the higher income will lead to less people willing to take insurance. I thought that it would make more sense that individuals with a higher income and who are risk averse, are willing to take more insurance.

**Comment by janboone** [comment]
"By increasing the income one could see that the equilibrium will change and less people will be insured which decreses the efficiency": indeed, this is the point we wanted you to see: everyone is risk averse and after the increase in income fewer people buy insurance; this is inefficient.

The reason why it happens: the inefficiency is due to adverse selection: relatively healthy people do not buy insurance because it is expensive. But it is expensive because only the worst risks buy insurance. If more people would buy insurance, insurance would become cheaper. This is the main argument in favor of mandatory health insurance as we have in the Netherlands.

If people are "very risk averse" they buy insurance even if it is expensive. This helps the efficiency of the market.

With the functions that we use in the notebook: what is the effect of income on the degree of risk aversion?
