### ISSUE TITLE
Questions Notebook financial crisis

### ISSUE THREAD

**Issue by florisvanlaarhoven** [janboone/applied-economics#27]
Hello,

Regarding the notebook on financial crisis I've got a couple of questions:

- What does a contract with a constant wage look like? I don't really understand the question. 
-  A more general question. Is still don't understand when we should use e.g. optimize.fsolve or when to use optimize.fmin. Could you explain this?

Kind regards,

Floris

**Comment by janboone** [comment]
Hi Floris,

* a constant wage is constant over the different states of nature: $w_g = w_a = w_b$; does this make sense?
* Suppose we have a function $f(x)$ (where $x$ can be a vector). If we want to solve the equation $f(x)=0$ (find the "zeros" of the function), we use `fsolve`
* if we want to solve $\min_x f(x)$ (minimize the function $f$ over $x$), we use `fmin`.

Does this solve your problems?

Jan.

**Comment by florisvanlaarhoven** [comment]
The first answer is now perfectly clear to me. However, I still don't really get when we should fsolve. Shouldn't we use that function when we set the derivative to zero:   f'(x)=0?. What would be the point of setting the function itself to 0 if we need to optimize the function?

**Comment by janboone** [comment]
A couple of things seem to get mixed up. 

Just to be clear" `optimize` is the name of the numpy library; it does not imply that we want to "optimize" the function.

To illustrate, we use `optimize.fsolve` on the function `excess_demand` when we want to determine the equilibrium price. This is equivalent to finding $x$ such that $f(x)=0$. This is not an optimization problem. We are not trying to minimize/maximize the function $f(x)$. We are looking for a price $p$ such that `excess_demand(p)=0`.

It is true that we can use `fsolve` to find minima/maxima by solving the first order condition $f'(x)=0$. But this requires that we first take (analytically or numerically) the derivative of $f$ w.r.t. $x$. In python it is usually easier to apply `optimize.fmin` directly to the function $f$ instead of applying `optimize.fsolve` to $f'$.

**Comment by florisvanlaarhoven** [comment]
Thank you, this clarifies a lot!
