### ISSUE TITLE
Interpretation of bank_choices and contract function

### ISSUE THREAD

**Issue by IvovanZitteren** [janboone/applied-economics#30]
Hello,

I am struggling a bit with the interpretation of the bank_choices and contract functions. When I run bank_choices(0.5) I get an output of [array([0.66043343, 0.94347633]), 0.7000000050116716]. I understand that this means that for an employee with a talent of 0.5, the optimal wage for the average (good) state is 0.66043343 (0.94347633) and that this employee will then choose q = 0.7 to maximize expected income. However, when I then run the contract function with 0.5 for ability, I get an output of 0.7 until I set outside_option larger than about 2.35 (because then, the function returns -1). This means that optimal risk choice will always be 0.7 and when the outside option of the employee is bigger than 2.35, the bank is better off by not hiring the employee.

My question is; why does the wage vector given by the bank_choice function not depend on the outside option of the employee?  If I understand the model correctly, the expected wage of the employee should be equal to their outside option. Does the wage vector therefore simply gives us the ratio of wage_average and wage_good rather than absolute amounts?

**Comment by janboone** [comment]
Great question! This is exactly what we like you to do: program the problem, look at the results and interpret the results. If you cannot find a sensible intuition, check your python code of the problem.

In this case, actually, your code is correct. There are two things to note. First, the bank has an additional instrument: a base wage; a wage the employee receives irrespective of the outcome. Think of this wage as being paid at the start of the year. By the end of the year the bank figures out whether on top of the base wage also a bonus needs to be paid. To simplify the code, we have left this out in the optimization problem of the employee. The wage is sunk at the moment the employee chooses her investment portfolio. The base wage makes sure that the outside option is met for the employee. You can see this in the function `contract` where the overall profit of the bank equals `profit` minus the expected wage paid. This expected wage is equal to `outside_option`.

Second, why does the bonus (and hence the investment portfolio) not depend on the outside option? Because there is no reason for the bank to introduce a distortion in the wage package of the employee as the outside option becomes higher. For each outside option it is optimal for the bank to induce the profit maximizing risk. Up till the point where the outside option is so high that it is no longer optimal to hire the employee in the first place.

When we combine moral hazard and adverse selection, we see that the risk increases as the outside option becomes higher.

Does this help?

Jan.

**Comment by IvovanZitteren** [comment]
Yes, this helps a lot! I did not realize that there was a base wage, now I understand the coding and the interpretation much better. I appreciate the quick response, many thanks!
