### ISSUE TITLE
Conda not able to download packages (geopandas)

### ISSUE THREAD

**Issue by 211sk** [janboone/applied-economics#51]
I am having a similar issue to this - https://github.com/conda-forge/geopandas-feedstock/issues/82

I have been trying to install geopandas on my conda, but it has been running for quite a few minutes with no response.

The code I used was -
conda install geopandas
but I also tried with pip install geopandas

**Comment by janboone** [comment]
As the issue suggests the problem is that  the latest python version causes problems when installing geopandas. The solution they mention is to create a new python environment with an earlier python version.
Creating a new python environment with conda and specifying the python version you want to use is described here:
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands

You can call this new environment 'geo'. Then in jupyterlab you can switch your kernel to 'geo'.
Note that the new environment is different from the default one. That is, you need to reinstall packages that are already available in your default environment, but not in the 'geo' environment. So do not panick if you suddenly see that a package is not available in 'geo'.

**Comment by 211sk** [comment]
Thank you so much! I will try this out!
